-- Reports — frozen, dated data-report snapshots (the "According to Legit.Show"
-- citation surface). Each report is a stable, dated artifact: once published, its
-- numbers don't move (so a citation of "94%" stays true), and a fresh edition is a
-- new row. Generated by a deterministic aggregation over listings.repo_audit (deep
-- code checks) + listings.benchmark (7 Frames). See austinpw-cloud/legitshow
-- dev_requests/07_report_generation + 05_according.

create table if not exists reports (
  id            uuid primary key default gen_random_uuid(),
  slug          text unique not null,
  kind          text not null default 'flagship',   -- flagship | category | theme | trend
  status        text not null default 'published',   -- draft | published
  title         text not null,
  subtitle      text,
  coined_term   text,                                 -- the ownable concept (e.g. "7-Frame trust gap")
  hero_stat     jsonb,                                -- { value, unit, label, n }
  sample        jsonb,                                -- { total, scope, as_of }
  stats         jsonb,                                -- [{ key, label, plain, fail_pct, n, status }]
  hall_of_fame  jsonb,                                -- [{ name, slug, pass, fail }]
  lowlights     jsonb,                                -- [{ name, slug, fail }]
  body          jsonb,                                -- optional narrative sections [{ h, md }]
  published_at  timestamptz not null default now(),
  created_at    timestamptz default now()
);
create index if not exists reports_published_idx on reports (status, published_at desc);

alter table reports enable row level security;
drop policy if exists "public read published reports" on reports;
create policy "public read published reports" on reports for select using (status = 'published');
grant select on reports to anon, authenticated;
